### ISSUE TITLE
No search results displayed on instant search page in Magento 2.2.8

### ISSUE THREAD

**Issue by gregkeene** [algolia/algoliasearch-magento-2#741] opened 2019-03-30 19:19 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

Currently developing a Magento 2 site. Using Magento 2.2.7 and Algolia Search 1.9.1, everything is fine. Using composer, I upgraded to Magento 2.2.8 and Algolia 1.10.0. After doing that, the autocomplete search works fine, but the instant search results page no longer returns any results. Instead, I am getting a javascript error message in the browser console. Screenshot of error message attached.

![algolia_screenshot](https://user-images.githubusercontent.com/7769822/55280648-d6c64680-52fe-11e9-89b4-8a6abc9d16fa.png)

**Bug: What is the current behavior?**
No search results returned. Error message in console.

**Bug: What is the expected behavior?**
Display of matching search results.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Issue is occurring on Magento 2.2.8 and Algolia 1.10.0. 
Reverting the site back to Magento 2.2.7 and Algolia 1.9.1 resolves the issue.

**Comment by damcou** [comment] 2019-04-01 09:26
Hello @gregkeene ,

Thanks for reaching out.
I just made some tests on my own and unfortunately, I can't reproduce the issue.
Could you please provide us a live URL where we can see it live ?

Thanks in advance.
Best.
Damien

**Comment by gregkeene** [comment] 2019-04-01 12:16
The site is still under development so I can't provide a publicly available URL.  I have extended the Algolia Search module in the site to add a pages section to the instant search results page. Perhaps that has something to do with the issue? Like I said the instant search results page doesn't return any results once the site is upgraded to Magento 2.2.8, but the pages section on the site does still return results (only the products section and category filter section are blank). I've attached a zip of the code I have placed in the app/design/frontend/<project>/<theme>/Algolia_AlgoliaSearch folder of the site. Perhaps you can tell me if there is an issue with this code that is causing the problem?

I've also attached a screenshot of the search results page under Magento 2.2.7 when it is working correctly. You can see the Pages section in the left sidebar that my custom code is adding to the page. Once upgraded to Magento 2.2.8, that section still displays, but the category filter above it doesn't and the product results section doesn't display either.

Thanks for any help you can provide on this.

[Algolia_AlgoliaSearch.zip](https://github.com/algolia/algoliasearch-magento-2/files/3029260/Algolia_AlgoliaSearch.zip)
![algolia_screenshot_2](https://user-images.githubusercontent.com/7769822/55326670-50247d00-5456-11e9-9671-4a011286dcd7.png)

**Comment by damcou** [comment] 2019-04-01 12:32
Have you tried to remove your custom code on your Magento 2.2.8 instance to see if it solves the issue ?

**Comment by gregkeene** [comment] 2019-04-01 13:46
I haven't but I'll try the upgrade again and see what happens.

**Comment by JanPetr** [comment] 2019-04-16 12:25
Hello @gregkeene, did you manage to solve it or do you still experience issues?
I'm closing the issue, but feel free to re-open if it doesn't work for you.

**Closed by JanPetr** 2019-04-16 12:25 UTC

**Comment by adarshkhatri** [comment] 2020-02-01 07:48
I tried in M2.3.3 but no results shown in the instant result page. I have right DOM element as well. No js error thrown either. What should I do?
