### ISSUE TITLE
CDN image url indexed with double slashes

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-magento-2#194] opened 2017-03-27 12:15 UTC
It seems like your image URL can be indexed with double slashes // while using a CDN resulting in 404 errors.

**Comment by aliasifmse** [comment] 2017-03-28 16:08
For all images this is the path indexed by algolia
https://d34lmvjs3crtl0.cloudfront.net/catalog/product/cache/2//165x165/beff4985b56e3afdbeabfc89641a4582/b/l/blackboard-collaborate-jpg.jpg

while actual path is
https://d34lmvjs3crtl0.cloudfront.net/catalog/product/cache/2/165x165/beff4985b56e3afdbeabfc89641a4582/b/l/blackboard-collaborate-jpg.jpg

Note : // in path which make it 404 

I disabled algolia extension and page shows fine

**Comment by aliasifmse** [comment] 2017-04-02 09:41
issue resolved by adding following line of code 
file : instantsearch.js
widget : algoliaBundle.instantsearch.widgets.hit
method : transformData
Code added
`hit.image_url = hit.image_url.replace(/2\/+/g, '2\/');`

**Comment by JanPetr** [comment] 2017-04-03 08:05
Hey @aliasifmse,
thanks for the notice.

Issue is that this code works for you, but it solves the consequence, not the root cause which is why the URL gets indexed with `//`.

Anyway, I'm happy you made it work and we will try to find out the reason for the bad indexing :) Thanks!

**Comment by aliasifmse** [comment] 2017-04-03 08:10
@JanPetr  very right , root cause still need to be fixed . thanks

**Closed** 2017-05-11 09:14 UTC
Labels: Bug, Investigate, Magento

**Comment by simonmaass** [comment] 2018-08-16 15:28
having the same issue - is this resolved?
