### ISSUE TITLE
Not getting products in algolia when Flat is disabled

### ISSUE THREAD

**Issue by parththummar** [algolia/algoliasearch-magento-2#708] opened 2019-03-06 15:34 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Products and categories are not getting indexed in algolia when the flat catalog is disabled.

**Bug: What is the expected behavior?**
The product should get indexed to algolia when the flat catalog is disabled.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.1.7 EE
Algolia: 1.10.0

**Comment by JanPetr** [comment] 2019-03-07 11:27
Hello @parththummar, thank you for the report. I'm going to investigate now and will come back to you.

**Comment by JanPetr** [comment] 2019-03-07 11:55
@parththummar I'm not able to reproduce it. I tried it with Flat catalog enabled and disabled and each time products were correctly indexed. Did you try to run Magento indexers after your disabled the flat catalog?

**Comment by parththummar** [comment] 2019-03-07 12:04
Hey @JanPetr 
I was able to get the products indexed, but categories are not getting indexed no matter what settings we choose.

**Comment by JanPetr** [comment] 2019-03-08 11:48
Hello @parththummar, 

that's good to hear, but it's really weird that categories are not indexed.

Could you try to downgrade to version 1.8.5 and see if categories get indexed on that version? Thank you!

**Comment by parththummar** [comment] 2019-03-08 11:53
Hello @JanPetr 
I have tried 1.8.5, 1.7.2 and dev-master
None of them able to index the categories, on another store I have 1.7.2 there I have Flat enabled and it's indexing the categories perfectly fine.

Note: I am using Commerce (Enterprise) Edition of the Magento.

**Comment by JanPetr** [comment] 2019-04-16 12:47
I tried that on Enterprise as well, @parththummar. It's really weird you're not able to get that indexed :// Did you manage to do some progress on that since March?

**Comment by parthaccorin** [comment] 2019-04-16 13:32
@JanPetr 
No, 
I tried dev version but not able to get the categories to algolia, so, unfortunately, we have to hide the category suggestions in search for now.

**Comment by bsuravech** [comment] 2019-07-14 14:56
Hi @parthaccorin,

Following up with this issue. We have had a few improvements added since this issue was last addressed. Have you been able to upgrade and has that resolved the issues you are having? If not, please let us know and we'll investigate further!

**Comment by damcou** [comment] 2019-12-30 13:36
Hello there, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue, feel free to respond and re-open the issue. Thank you!

**Closed by damcou** 2019-12-30 13:36 UTC
Labels: Investigating
