### ISSUE TITLE
Website specific categories are shown on other websites

### ISSUE THREAD

**Issue by maximbaibakov** [algolia/algoliasearch-magento-2#275] opened 2017-07-03 00:52 UTC
Hi there,

We have multi website setup (3 websites).
Each of the website has own category tree (3 root categories). Some of the categories have the same name.

When we are doing search on 1 website, we are observing categories (with the same name) from another website.

I had a look on in Indices in Algolia backend and noticed that website Indice contains records from other 2 websites.

Is there known bug / any suggestions?

Regards,
Maxim

**Comment by JanPetr** [comment] 2017-07-03 10:35
Thanks for reporting that @maximbaibakov,

I'll investigate and come back to you when I have something.

**Comment by JanPetr** [comment] 2017-07-04 12:19
Hello Maxim,

I investigated the issue, but I'm not able to reproduce. Even when my store has a different root category, only the correct categories are indexed.
Would you mind sharing with me your website(s) where I could see the issue live and see what's happening there?
And if you could share with me your detailed setup of stores and root categories (maybe with screenshots from admin) it'd be really helpful!

Thanks a lot for your help 💯

**Comment by maximbaibakov** [comment] 2017-07-05 03:50
Hey @JanPetr 

I do not really want to share the website URL / Algolia account / Index name on public, if there is a way to send the information privately, happy to do this.


![Uploading Screen Shot 2017-07-05 at 1.44.54 pm.png…]()
![Uploading Screen Shot 2017-07-05 at 1.39.39 pm.png…]()

Also, please find a few screenshots:
- Screenshot from admin which shows the overall category tree structure, each of the Root category assigned to different websites as root category. Is there something related to name? probably... as you can see both root categories have same child category name.
- Second screenshot shows result from Algolia on frontend, first category "Heels" is from different website (this should not be here), the second category "Shop hers / Heels" it is correct category.
ges.githubusercontent.com/876516/27848489-db480360-6188-11e7-983f-f729b7fcb66a.png)
Let me know, if there is anything else which could help you

Regards,
Maxim

**Comment by maximbaibakov** [comment] 2017-07-19 01:47
Hi @JanPetr 

Do you have any update on this one?

Regards,
Maxim

**Comment by Sanfam** [comment] 2017-11-01 14:46
@JanPetr , I can confirm encountering this same issue on my Magento 2 store.  I'm running a single Magento 2.1.7 storefront (Launched on 2.0.5) with 4 websites/domains being served, each with their own website-linked category trees.  Algolia 1.3.0 is installed and is running a largely-stock configuration.

In most cases, our sites share identical category names and may even have products with the same name (though these could be either duplicated bundled products with store-unique content, or simple products shared between stores) assigned to them.  

This is easily triggered on the front-end by searching for a keyword where products may be assigned to both store categories:

Example: Searching for "ECM":
![image](https://user-images.githubusercontent.com/3504427/32280258-9d2e563a-bef1-11e7-93df-81a71127314b.png)

The top category referenced is assigned to the store presently being displayed and is a member of its assigned category tree; It is accessible by clicking the link.  The bottom category, sharing the same name, is assigned to another domain and is a part of that domain's unique category tree.  Clicking its link returns a 404.

**Comment by Sanfam** [comment] 2017-11-01 16:02
An additional observation: `include in menu` seems to act inconsistently for other store scopes.  Brands on Site 1 all have `include in menu` set to `no`, but show in the list of categories provided by the autocomplete widget.  Brands on Site 2 all have `include in menu` set to `yes` and show, but are removed when changed to `no`.

**Comment by JanPetr** [comment] 2017-11-22 13:29
Hello @Sanfam and @maximbaibakov,

could you try to apply #366 fix and see if it helped you?

**Closed** 2017-12-12 15:23 UTC

**Comment by peterjaap** [comment] 2019-04-17 08:48
This issue regressed (I guess after the refactoring the category logic to `Helper/Entity/CategoryHelper.php`). See for a workaround https://github.com/algolia/algoliasearch-magento-2/pull/755
