### ISSUE TITLE
Magento 2.2.6 EE failed algolia_products reindex

### ISSUE THREAD

**Issue by jcodo** [algolia/algoliasearch-magento-2#619] opened 2018-11-21 09:28 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**Bug: What is the current behavior?**

When running `bin/magento indexer:reindex algolia_products` on Magento EE 2.2.6, reindex fails with SQL error message...

```
Algolia Search Products indexer process unknown error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_value.value' in 'field list', query was: SELECT `entity`.`sku`, `product_entity`.`entity_id` AS `product_id`, `attribute`.`attribute_code`, `entity_value`.`value` AS `value_index`, `attribute_label`.`value` AS `super_attribute_label`, IFNULL(option_value.value, default_option_value.value) AS `option_title`, `default_option_value`.`value` AS `default_title` FROM `catalog_product_super_attribute` AS `super_attribute`
 INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.row_id = super_attribute.product_id AND (product_entity.created_in <= 1 AND product_entity.updated_in > 1)
 INNER JOIN `catalog_product_super_link` AS `product_link` ON product_link.parent_id = super_attribute.product_id
 INNER JOIN `eav_attribute` AS `attribute` ON attribute.attribute_id = super_attribute.attribute_id
 INNER JOIN `catalog_product_entity` AS `entity` ON entity.entity_id = product_link.product_id AND (entity.created_in <= 1 AND entity.updated_in > 1)
 INNER JOIN `catalog_product_entity` AS `entity_value` ON entity_value.attribute_id = super_attribute.attribute_id AND entity_value.store_id = 0 AND entity_value.row_id = entity.row_id AND (entity_value.created_in <= 1 AND entity_value.updated_in > 1)
 LEFT JOIN `catalog_product_super_attribute_label` AS `attribute_label` ON super_attribute.product_super_attribute_id = attribute_label.product_super_attribute_id AND attribute_label.store_id = 0
 LEFT JOIN `eav_attribute_option` AS `attribute_option` ON attribute_option.option_id = entity_value.value
 LEFT JOIN `eav_attribute_option_value` AS `option_value` ON option_value.option_id = entity_value.value AND option_value.store_id = 1
 LEFT JOIN `eav_attribute_option_value` AS `default_option_value` ON default_option_value.option_id = entity_value.value AND default_option_value.store_id = 0 WHERE (super_attribute.product_id = 3241) AND (attribute.attribute_id = '') ORDER BY `attribute_option`.`sort_order` ASC
```

**Bug: What is the expected behavior?**
Every other required algolia index successfully reindexes. Looking into other issues, #522 may suggest that the B2B modules are interfering some how? However, reindex also fails when these modules are disabled.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento Enterprise 2.2.6
Algolia Search Magento 2 version 1.8.3

**Comment by JanPetr** [comment] 2019-02-14 12:15
Hello @jcodo,

thank you for the report.
Can you reproduce the issue on the latest version (1.9.1) of the extension?

It's been a while since it was reported. I'm closing the issue now. If you have more information or you still experience the issue on the latest version, feel free to re-open.

**Closed by JanPetr** 2019-02-14 12:15 UTC

**Comment by dzls** [comment] 2019-03-28 16:39
Hi. I'm getting the same error. Algolia 1.10.0 (latest version), Magento/2.2.5 (Community). Same behaviour/expectations. Should open a new issue? It would be mainly the same. Thanks!

**Comment by jcodo** [comment] 2019-04-23 14:09
This is still an issue for me @JanPetr. Now on Magento Enterprise 2.3.1 and module version 1.10.0
