### ISSUE TITLE
Not indexing categories in Magento 2.1

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#47] opened 2016-08-12 13:48 UTC
**Preconditions:**

1. Magento 2.1
2. PHP 7.0.8
3. MySQL 5.7.13

**Result:** 
Categories are not indexed in Magento 2.1. It`s empty. but products are indexed perfect.
Not indexed all categories - included or not in menu.
By the way - Helper\Entity\CategoryHelper.php line 91:
Selected all categories included in menu, but is it depends by settings  
Algolia Search->Categories->Show categories that are not included in the navigation menu ?

**Comment by JanPetr** [comment] 2016-08-12 13:52
Hello @vmalyk,
did you check Algolia Dashboard that categories are not really indexed? 
There is a bug that attribute `include_in_menu` is not indexed within categories and therefore you do not get any categories in autocomplete menu because, depending on settings, it fetches only categories which has attribute `include_in_menu` set to 1.
The bug is fixed in #46.

**Comment by vmalyk** [comment] 2016-08-12 13:54
Yes, It`s empty: http://prntscr.com/c4uky0. For products: http://prntscr.com/c4ulg2

**Comment by JanPetr** [comment] 2016-08-12 13:58
Thanks for checking. I tried but I'm not able to reproduce. What is your category settings? Can you investigate here: https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Data.php#L224-L240 That categories are fetched and that collection has any size and if categories are then processed correctly?

**Comment by vmalyk** [comment] 2016-08-13 19:38
Thank you for help. After research looks as collection isn`t loaded. getSize() returns correct value, but in https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Data.php#L403   foreach doesn`t work and objects are not added.

**Comment by JanPetr** [comment] 2016-08-13 19:40
Thank you for your investigation @vmalyk. Do you know why foreach doesn't iterate over real categories?

**Comment by vmalyk** [comment] 2016-08-13 19:46
In [https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Data.php#L393-L396](here) used  \Magento\Catalog\Model\ResourceModel\Category\Flat\Collection but $collectionDefault has type \Magento\Catalog\Model\ResourceModel\Category\Collection. Looks Magento has difference how need init and load these collections

**Comment by JanPetr** [comment] 2016-08-15 13:07
Did you manage to make it work @vmalyk? 
I checked and there was ust bad annotation. Collection was still instance of `\Magento\Catalog\Model\ResourceModel\Category\Collection`, only annotation said it was `\Magento\Catalog\Model\ResourceModel\Category\Flat\Collection`. I fixed it in #51.

**Comment by JanPetr** [comment] 2016-10-18 12:50
Is the issue related to #87 ?

**Comment by vmalyk** [comment] 2016-10-22 05:29
Hi, yes they are related. I see your pull request PR/#87 and you check Magento version. I propose to add small improvement - add public getter for idColumn and create module with Plugin  for this getter to get another column name - row_id. For Magento EE 2.1 this module would be depend on 2 modules: Magento_CatalogStaging and Algolia_AlgoliaSearch.

**Comment by JanPetr** [comment] 2016-10-24 12:23
Thanks for you suggestion @vmalyk, but I'm not sure about another plugin as it will increase complexity and time required for maintaining the extension. And it will be complex to install it from Magento Commerce as the extension'd require not one but two plugins. I don't see advantage of another plugin which would weight disadvantages.
Is there something I cannot see right now?

**Comment by JanPetr** [comment] 2016-10-24 16:30
Fixed in [1.0.3](https://github.com/algolia/algoliasearch-magento-2/releases/tag/1.0.3)

**Closed by JanPetr** 2016-10-24 16:30 UTC
Labels: bug, EE

**Comment by shujaatonline** [comment] 2019-02-19 04:51
Hello Jan,
How can i get product category on hit.phtml file

following not working. can you plz check
{{#course_category}}
                          <li><span  ></span> {{ course_category }}</li>
                          {{/course_category}}
