### ISSUE TITLE
Multistore products not working

### ISSUE THREAD

**Issue by tcmarketing** [algolia/algoliasearch-magento-2#711] opened 2019-03-08 16:56 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When using a multistore with different products between each store the product links are incorrect, linking to other store views

**Bug: What is the expected behavior?**
Products link to the correct store

**Bug: What is the proposed solution?**
Unknown

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia Version - 1.10.0
Magento Version - 2.2.6

**Comment by damcou** [comment] 2019-03-11 11:00
Hello @tcmarketing ,

Thanks for reaching out.

By default, the extension indexes the products for each active store.
During the process, the storeId is applied on the product object and the url is fetched using a standard Magento method so this should work (I tried it on my side and I don't have the issue).

Could you provide an url where we can see the issue live ? 

Let us know.
Best.
Damien

**Comment by peterjaap** [comment] 2019-03-12 09:31
We're also having this issue, but only when we do a full reindex. I'll try to investigate today.

**Comment by peterjaap** [comment] 2019-03-12 09:36
Here's a very dirty and very temporary script to 'fix' the issue after the wrong base URL has been used (it's always the same wrong base URL in our case, it's (probably not coincidentally) the base URL of our most recently added store.

```
<?php

require_once 'vendor/algolia/algoliasearch-client-php/algoliasearch.php';

$client = new \AlgoliaSearch\Client('APP_ID_HERE', 'API_KEY_HERE');

$indexes = $client->listIndexes();
$indexes = array_shift($indexes);

foreach ($indexes as $index) {
    $indice = $client->initIndex($index['name']);
    foreach ($indice->browse('') as $hit) {
        if (
            <do some checks here to see if the object contains the wrong urls>
        ) {
            if($index['name'] == 'INSERT_INDEX_NAME_HERE') {
                $baseUrl = 'www.yourbaseurl.com';
            } elseif($index['name'] == 'INSERT_ANOTHER_INDEX_NAME_HERE') {
                $baseUrl = 'www.yourotherbaseurl.com';
            } else {
                continue;
            }

            $wrongBaseUrl = 'INSERT_WRONG_BASE_URL_HERE';

            $hit['url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['url']);
            $hit['thumbnail_url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['thumbnail_url']);
            $hit['image_url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['image_url']);
            if(isset($hit['images_data'])) {
                foreach ($hit['images_data'] as $key=>$value) {
                    $hit['images_data'][$key] = str_replace($wrongBaseUrl, $baseUrl, $value);
                }
            }

            echo 'Saving ' .$hit['objectID'] . PHP_EOL;
            $indice->saveObject($hit);
        }
    }
}
```

**Comment by tcmarketing** [comment] 2019-03-14 09:22
> Here's a very dirty and very temporary script to 'fix' the issue after the wrong base URL has been used (it's always the same wrong base URL in our case), it's probably not coincidentally the base URL of our most recently added store.
> 
> ```
> <?php
> 
> require_once 'vendor/algolia/algoliasearch-client-php/algoliasearch.php';
> 
> $client = new \AlgoliaSearch\Client('APP_ID_HERE', 'API_KEY_HERE');
> 
> $indexes = $client->listIndexes();
> $indexes = array_shift($indexes);
> 
> foreach ($indexes as $index) {
>     $indice = $client->initIndex($index['name']);
>     foreach ($indice->browse('') as $hit) {
>         if (
>             <do some checks here to see if the object contains the wrong urls>
>         ) {
>             if($index['name'] == 'INSERT_INDEX_NAME_HERE') {
>                 $baseUrl = 'www.yourbaseurl.com';
>             } elseif($index['name'] == 'INSERT_ANOTHER_INDEX_NAME_HERE') {
>                 $baseUrl = 'www.yourotherbaseurl.com';
>             } else {
>                 continue;
>             }
> 
>             $wrongBaseUrl = 'INSERT_WRONG_BASE_URL_HERE';
> 
>             $hit['url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['url']);
>             $hit['thumbnail_url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['thumbnail_url']);
>             $hit['image_url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['image_url']);
>             if(isset($hit['images_data'])) {
>                 foreach ($hit['images_data'] as $key=>$value) {
>                     $hit['images_data'][$key] = str_replace($wrongBaseUrl, $baseUrl, $value);
>                 }
>             }
> 
>             echo 'Saving ' .$hit['objectID'] . PHP_EOL;
>             $indice->saveObject($hit);
>         }
>     }
> }
> ```

Hi, 

Is this replacing a file or a new file to be made, we also have 3 stores in our multistore so not sure if this will fix it or not but would like to try it.

**Comment by peterjaap** [comment] 2019-03-14 09:29
No this is a completely seperate file that we run manually when this problem occurs.

**Comment by tcmarketing** [comment] 2019-03-14 09:31
> No this is a completely seperate file that we run manually when this problem occurs.
I'll give it a test thanks

**Comment by tcmarketing** [comment] 2019-03-14 09:41
> No this is a completely seperate file that we run manually when this problem occurs.

How are you running this file may I ask?

**Comment by peterjaap** [comment] 2019-03-14 09:51
Just save it in the project dir and run `php yourfilename.php`

**Comment by tcmarketing** [comment] 2019-03-14 09:54
> Just save it in the project dir and run `php yourfilename.php`. Be sure to customize as needed, out of the box it won't work.

Do you have an example of this bit "do some checks here to see if the object contains the wrong urls"

**Comment by tcmarketing** [comment] 2019-03-14 10:19
> We do something like this;
> 
> ```
>         if (
>             stripos($hit['url'], $partOfWrongBaseUrl) !== false
>             || stripos($hit['image_url'], $partOfWrongBaseUrl) !== false
> 	    || (isset($hit['images_data']) && stripos(json_encode($hit['images_data']), $partOfWrongBaseUrl) !== false)
>         ) {
> ```

I have tried the following and it doesn't seem to work?

`<?php

require_once 'vendor/algolia/algoliasearch-client-php/algoliasearch.php';

$client = new \AlgoliaSearch\Client('xxxx', 'xxxxx');

$indexes = $client->listIndexes();
$indexes = array_shift($indexes);

foreach ($indexes as $index) {
    $indice = $client->initIndex($index['name']);
    foreach ($indice->browse('') as $hit) {
        if (
          stripos($hit['url'], $partOfWrongBaseUrl) !== false
        ) {
            if($index['name'] == 'ustradesite_usa_products') {
                $baseUrl = 'paladone.tcmarketing.co.uk/usa/';
            } elseif($index['name'] == 'uktradestore_ukb2b_products') {
                $baseUrl = 'paladone.tcmarketing.co.uk/ukb2b/';
            } elseif($index['name'] == 'ukb2cstore_ukb2c_products') {
                $baseUrl = 'paladone.tcmarketing.co.uk/ukb2c/';
            } else {
                continue;
            }

            $wrongBaseUrl = 'paladone.tcmarketing.co.uk/ukb2c/';
            $partOfWrongBaseUrl = 'paladone.tcmarketing.co.uk/ukb2c';

            $hit['url'] = str_replace($wrongBaseUrl, $baseUrl, $hit['url']);

            echo 'Saving ' .$hit['objectID'] . PHP_EOL;
            $indice->saveObject($hit);
        }
    }
}`

Any idea?

**Comment by tcmarketing** [comment] 2019-03-27 09:32
Running a URL fixer code but don't think this is a great way of solving the issue, the developer of this module really needs to fix it..

**Comment by tcmarketing** [comment] 2019-04-11 11:26
> We do something like this;
> 
> ```
>         if (
>             stripos($hit['url'], $partOfWrongBaseUrl) !== false
>             || stripos($hit['image_url'], $partOfWrongBaseUrl) !== false
> 	    || (isset($hit['images_data']) && stripos(json_encode($hit['images_data']), $partOfWrongBaseUrl) !== false)
>         ) {
> ```

Hi, we have come up with a better fix than this just to let you know see below

/public_html/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper

Line 456 add
`$newURL = $product->getUrlModel()->getUrl($product, $urlParams);`

Directly below find 'url' and replace with, replace the storeurl/code with yours

` 'url'                => str_replace(array('https://STOREURL1/STORECODE1/', 'https://STOREURL2/STORECODE2/', 'https://STOREURL3/STORECODE3/'), array('', '', ''), $newURL),`

/public_html/vendor/algolia/algoliasearch-magento-2/view/frontend/templates/instant/hit.phtml

Line 15

Add 

`<?php echo $block->getBaseUrl(); ?>`

Before

`{{url}}`

Do the same in

/public_html/vendor/algolia/algoliasearch-magento-2/view/frontend/templates/autocomplete/

For the following files

page.phtml
product.phtml
suggestion.phtml

You can then run the index and it will always have the correct URL structure!

**Comment by peterjaap** [comment] 2019-04-17 08:58
@tcmarketing thanks, we did a similar thing but decided not to touch the data in the index but only to change the URLs in runtime on the frontend, see https://github.com/algolia/algoliasearch-magento-2/issues/576

**Comment by peterjaap** [comment] 2019-04-17 12:03
@tcmarketing that doesn't fix everything bytheway, we also get storecodes attached to the original URL, as in `?___store=storecode`

**Comment by tomkingfisher** [comment] 2019-05-28 09:12
Our product links are fine however, we have an issue with the Categories linking to the default store rather than the store that it should go to.

**Comment by peterjaap** [comment] 2019-08-05 09:02
@bsuravech @JanPetr any update? This is starting to get really annoying... porting tickets to an internal system isn't really transparent either, makes it a black box process for us!!

**Comment by bsuravech** [comment] 2019-08-05 09:22
Hi @peterjaap ! Thanks for the ping! Following the thread above, are the product links still an issue in the current version? 

For @tomkingfisher, the category issue has been addressed in PR #826 in regards to store emulation. Can you try patching with this PR and let us know if that helps you out?

**Comment by peterjaap** [comment] 2019-08-05 09:23
@bsuravech yes they are still an issue

**Comment by peterjaap** [comment] 2019-08-06 08:32
So here's some more info:

I have 6 stores; store ID 1 through 6.

When I run a full reindex, the **second-to-last** store to be reindexed gets URLs with the base URL and the storecode of the **last** store.

So this usually is store ID 5 which has URLs from store ID 6. But when I reindex all stores exccept ID 5, store ID 4 gets the URLs from store ID 6. And if I reindex all except 6, store ID 4 gets the URLs from store ID 5....

**Comment by peterjaap** [comment] 2019-08-06 08:32
So here's some more info:

I have 6 stores; store ID 1 through 6.

When I run a full reindex, the **second-to-last** store to be reindexed gets URLs with the base URL and the storecode of the **last** store.

So this usually is store ID 5 which has URLs from store ID 6. But when I reindex all stores exccept ID 5, store ID 4 gets the URLs from store ID 6. And if I reindex all except 6, store ID 4 gets the URLs from store ID 5....

**Comment by peterjaap** [comment] 2019-08-06 10:44
So it seems the ProductHelper sometimes (for some products, but not always the same products) looses track of which store were supposed to reindex. It then defaults to the last store.

**Comment by peterjaap** [comment] 2019-08-06 11:00
In the function `\Algolia\AlgoliaSearch\Helper\Data::getProductsRecords` there's a foreach statement, which loops over the collection and retrieves data.

Since the process looses track of the current store in the storemanager, we can set this again by running `$this->storeManager->setCurrentStore($storeId);`.

When I run this **before** the foreach statement, the wrong URLs are sometimes returned. When I run this **inside** the foreach statement, all URLs are correct.

This leads me to believe that somewhere in the foreach loop, maybe for a specific product, the current store value in the store manager is reset or emptied.

**Comment by peterjaap** [comment] 2019-08-06 12:16
So after a whole lot of debugging, it turns out this is something weird in Magento, not Algolia related (Algolia just uses the Magento code in such a way that it triggers). The problem is that we had 2 products that were imported as configurables, but didn't have any child products. For some reason which I don't care about right now, Magento then looses the current store set in the store manager.

The fix was to disable those products (they couldn't be sold anyway). Here's a query to test whether you have such products in your database;

```
SELECT entity_id, COUNT(product_id) as cnt FROM catalog_product_entity cpe LEFT JOIN catalog_product_super_link cpsl ON cpe.entity_id = cpsl.parent_id WHERE cpe.type_id = 'configurable' GROUP BY cpe.entity_id HAVING cnt = 0
```

Just saving the product actually fixes the issue, because when you save a configurable product that doesn't have child products, it's automatically converted to a simple product. And the code that tripped us up is not run for simple products.

**Comment by peterjaap** [comment] 2019-08-07 09:38
So after 3 days of debugging, it turns out it was related to a totally different (custom) extension that threw us off :(

**Comment by peterjaap** [comment] 2019-11-28 09:38
It seems this fixed with https://github.com/algolia/algoliasearch-magento-2/pull/826 now.

**Comment by damcou** [comment] 2019-12-30 13:37
Indeed ! I close it :).

**Closed by damcou** 2019-12-30 13:37 UTC
Labels: Ported to Jira
