### ISSUE TITLE
Display Mode : "Static Block Only" option not working on categories

### ISSUE THREAD

**Issue by PriyankaJ101** [algolia/algoliasearch-magento-2#743] opened 2019-04-01 12:44 UTC
**Bug: What is the current behavior?**
While assigning categories to "Static Block Only" option under admin->Catalog->Category page, the categories can't render the cms block contents on staging frontend. But this is happening since we started using the Algolia search.

![image](https://user-images.githubusercontent.com/34852743/55327991-fac58b80-54a8-11e9-93a8-726395aa544d.png)

![image](https://user-images.githubusercontent.com/34852743/55328017-0c0e9800-54a9-11e9-8f45-9a391b9001fa.png)

**Bug: What is the expected behavior?**
Cms blocks contents should be rendered while assigning any categories to "Static Block Only" option under admin->manage categories page 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.6 EE (Cloud)
Algolia 1.10.0

**Comment by damcou** [comment] 2019-04-01 13:13
Hello @PriyankaJ101 ,

Thanks for reaching out.
I had a look at your issue and I couldn't reproduce it on my own (when I select "Static block only", the block is showing up as expected).
I see that you're getting an error on your frontend, you should have an error logged in your var/system.log or var/exception.log files. Could you please monitor them and send us the error you get when you try to display the page ?

Thanks in advance.
Best.
Damien

**Comment by PriyankaJ101** [comment] 2019-04-01 13:44
Hello Damien,

There is no such specific errors on var/log/system.log and var/log/exception.log while accessing category page on frontend on staging.

kxcqifso6kvqm_stg@i-03a9489273ea99b95:~/var/log$ tail -f exception.log
Class Magento\\Framework\\Notification\\NotifierInterface\\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. at /app/kxcqifso6kvqm_stg/vendor/magento/framework/Code/Generator.php:135)"} []
[2019-04-01 13:36:04] report.CRITICAL: Can't create directory /app/kxcqifso6kvqm_stg/generated/code/Magento/Framework/Notification/NotifierInterface/.
Class Magento\Framework\Notification\NotifierInterface\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. {"exception":"[object] (RuntimeException(code: 0): Can't create directory /app/kxcqifso6kvqm_stg/generated/code/Magento/Framework/Notification/NotifierInterface/.
Class Magento\\Framework\\Notification\\NotifierInterface\\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. at /app/kxcqifso6kvqm_stg/vendor/magento/framework/Code/Generator.php:135)"} []
[2019-04-01 13:41:00] report.CRITICAL: Can't create directory /app/kxcqifso6kvqm_stg/generated/code/Magento/Framework/Notification/NotifierInterface/.
Class Magento\Framework\Notification\NotifierInterface\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. {"exception":"[object] (RuntimeException(code: 0): Can't create directory /app/kxcqifso6kvqm_stg/generated/code/Magento/Framework/Notification/NotifierInterface/.
Class Magento\\Framework\\Notification\\NotifierInterface\\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. at /app/kxcqifso6kvqm_stg/vendor/magento/framework/Code/Generator.php:135)"} []
[2019-04-01 13:41:00] report.CRITICAL: Can't create directory /app/kxcqifso6kvqm_stg/generated/code/Magento/Framework/Notification/NotifierInterface/.
Class Magento\Framework\Notification\NotifierInterface\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. {"exception":"[object] (RuntimeException(code: 0): Can't create directory /app/kxcqifso6kvqm_stg/generated/code/Magento/Framework/Notification/NotifierInterface/.
Class Magento\\Framework\\Notification\\NotifierInterface\\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. at /app/kxcqifso6kvqm_stg/vendor/magento/framework/Code/Generator.php:135)"} []
^C


kxcqifso6kvqm_stg@i-03a9489273ea99b95:~/var/log$ tail -f system.log
[2019-04-01 13:42:21] report.INFO: Cron Job order_cleanup is run [] []
[2019-04-01 13:42:21] report.INFO: Cron Job order_cleanup is successfully finished. Statistics: {"sum":0.0026431083679199,"count":1,"realmem":0,"emalloc":1904,"realmem_start":176160768,"emalloc_start":164793352} [] []
[2019-04-01 13:42:21] report.INFO: Cron Job staging_synchronize_entities_period is successfully finished. Statistics: {"sum":0.0043678283691406,"count":1,"realmem":0,"emalloc":22040,"realmem_start":176160768,"emalloc_start":163985288} [] []
[2019-04-01 13:42:21] report.INFO: Cron Job consumers_runner is run [] []
[2019-04-01 13:42:21] report.INFO: Cron Job consumers_runner is successfully finished. Statistics: {"sum":0.002640962600708,"count":1,"realmem":0,"emalloc":1904,"realmem_start":176160768,"emalloc_start":160529024} [] []
[2019-04-01 13:42:21] report.INFO: Cron Job indexer_update_all_views is successfully finished. Statistics: {"sum":0.77575516700745,"count":1,"realmem":6291456,"emalloc":18985072,"realmem_start":176160768,"emalloc_start":160726552} [] []
[2019-04-01 13:42:21] report.INFO: Cron Job indexer_reindex_all_invalid is run [] []
[2019-04-01 13:42:21] report.INFO: Cron Job indexer_reindex_all_invalid is successfully finished. Statistics: {"sum":0.033874988555908,"count":1,"realmem":0,"emalloc":470424,"realmem_start":176160768,"emalloc_start":160268416} [] []
[2019-04-01 13:42:21] report.INFO: Cron Job indexer_update_all_views is run [] []
[2019-04-01 13:42:22] report.INFO: Cron Job indexer_update_all_views is successfully finished. Statistics: {"sum":0.74326920509338,"count":1,"realmem":6291456,"emalloc":18985072,"realmem_start":176160768,"emalloc_start":160740984} [] []


Thanks,
Priyanka

**Comment by damcou** [comment] 2019-04-04 13:46
Hello there,

Did you find more information about the 503 errors you get ?
Maybe in your server logs ?

Let us know.

**Comment by PriyankaJ101** [comment] 2019-04-04 14:43
Hello,

I am getting below error while associating "Static Block Only" option to any categories.

Error: Uncaught exception 'Error' with message 'Call to a member function getPageSize() on null' in /app/kxcqifso6kvqm_stg/shared/app/code/Packt/GoogleTagManager/Block/SearchObject.php:105
in Packt\GoogleTagManager\Block\SearchObject::getGaConfig called at /app/kxcqifso6kvqm_stg/shared/app/code/Packt/GoogleTagManager/view/frontend/templates/ga.phtml (7)
in include called at /app/kxcqifso6kvqm_stg/vendor/magento/framework/View/TemplateEngine/Php.php (59)
in Magento\Framework\View\TemplateEngine\Php::render called at /app/kxcqifso6kvqm_stg/vendor/magento/framework/View/Element/Template.php (270)
in Magento\Framework\View\Element\Template::fetchView called at /app/kxcqifso6kvqm_stg/vendor/magento/framework/View/Element/Template.php (300)
in Magento\Framework\View\Element\Template::_toHtml called at /app/kxcqifso6kvqm_stg/vendor/magento/module-google-tag-manager/Block/ListJson.php (149)
in Magento\GoogleTagManager\Block\ListJson::_toHtml called at /app/kxcqifso6kvqm_stg/vendor/magento/framework/View/Element/AbstractBlock.php (667)


Thanks,
Priyanka

________________________________

**Comment by damcou** [comment] 2019-04-04 15:29
Seems that there's a conflict with a module which seems to be in "Packt/GoogleTagManager". Have tried to investigate further or temporary disable this module ?

**Comment by JanPetr** [comment] 2019-04-16 12:24
@PriyankaJ101, did you manage to solve the issue or do you still experience issues?
I'm closing the issue, but feel free to re-open :)

**Closed by JanPetr** 2019-04-16 12:24 UTC
