### ISSUE TITLE
High amount of deletions

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-magento-2#191] opened 2017-03-24 14:30 UTC
We had a few people reporting that they had a high amount of deletion in the API logs. Hence the number of operations grew exponentially.

We should make sure that there are nothing wrong with the extension.

**Comment by JanPetr** [comment] 2017-05-02 09:55
@julienbourdeau Did you investigate? Did you manage to find something yet? Did we receive any recent reports of that?

**Comment by julienbourdeau** [comment] 2017-05-02 13:05
I don't think we had report recently. I checked the way queue and reindexing was handled but I couldn't find anything. Since we can't reproduce it, it's really hard to track.

**Comment by JanPetr** [comment] 2017-05-02 13:07
ok, closing it for now as we're not able to reproduce

**Closed by JanPetr** 2017-05-02 13:07 UTC
