### ISSUE TITLE
Weird URLs appearing in Google Analytics

### ISSUE THREAD

**Issue by seagyn** [algolia/algoliasearch-magento-2#352] opened 2017-11-14 10:46 UTC
Hi there,

Since we installed Algolia, we've been getting weird paths in our Analytics results (with unicode). Not sure why and can't replicate it on my side.

<img width="700" alt="screen shot 2017-11-14 at 9 33 28 am" src="https://user-images.githubusercontent.com/743964/32776009-cfb260fe-c939-11e7-8212-10d6c10d3c84.png">

**Comment by JanPetr** [comment] 2017-11-15 17:32
Hello @seagyn,
do you have enabled [Analytics](https://community.algolia.com/magento/doc/m1/analytics/) feature of the extension?

**Comment by JanPetr** [comment] 2017-11-27 08:53
I'm closing the issue since I didn't manage to reproduce and didn't hear from you back @seagyn.
If you still experience the issue, feel free to re-open.

**Closed by JanPetr** 2017-11-27 08:53 UTC

**Comment by JammyClarkie** [comment] 2017-12-12 14:55
Interestingly, I'm also getting this issue with Magento 2.2 (not Algolia)

**Comment by windowbox** [comment] 2018-02-21 21:53
Please reopen this, I have a similar issue and am seeing it in multiple installations CE and EE related to 2.2.

The easiest way to observe this is to look at a fresh 2.2.2 install and on the default homepage search in source for "Magento_Ui/js/block-loader"

Pre 2.2 the following looked like: 
"Magento_Ui/js/block-loader": "http://magento2-demo.nexcess.net/pub/static/frontend/Magento/luma/en_US/images/loader-1.gif"

and now it looks like (from a different installation):

"Magento_Ui/js/block-loader": "http\u003A\u002F\u002Fmagento2.codazon.com\u002Ffastest\u002Fpub\u002Fstatic\u002Ffrontend\u002FCodazon\u002Ffastest_furniture\u002Fen_US\u002Fimages\u002Floader\u002D1.gif"

I assume this is consistent throughout the installation on multiple js files for different modules. I've seen it for Magento_reviews and Google analytics.
