### ISSUE TITLE
Required parameter 'theme_dir' was not passed

### ISSUE THREAD

**Issue by webtekindo** [algolia/algoliasearch-magento-2#771] opened 2019-05-07 08:44 UTC
Magento 2.3.1
Algolia 1.10.0
Custom theme

When install Algolia and run: _bin/magento setup:upgrade_

We have an error:
_Running data recurring...Required parameter 'theme_dir' was not passed_

If we disable Algolia_AlgoliaSearch, then we have no issue running setup:upgrade.

Do you know what is the issue?

**Comment by damcou** [comment] 2019-05-07 09:45
Hello @webtekindo ,

Thanks for reaching out.
Unfortunately, I'm not able to reproduce this issue, and it's the very first time we have such feedback from our users. 

If you're using a custom theme, this should be related to that. Could you please have a look at this thread to see if that helps : https://magento.stackexchange.com/questions/100011/required-parameter-theme-dir-was-not-passed

Let us know.
Best.

**Comment by webtekindo** [comment] 2019-05-07 11:32
Magento 2.3.1
Algolia 1.10.0

I completely remove the custom template from files and database following:

https://magento.stackexchange.com/questions/100011/required-parameter-theme-dir-was-not-passed
http://blog.netgloo.com/2016/05/18/uninstall-and-reinstall-a-magento-2-custom-theme/

I select Luma theme, but still I have the same error.

If I disable 'Algolia_AlgoliaSearch' => 0 (in config.php), then no problem setup:upgrade is successfull.

So not sure where the issue is?

**Comment by webtekindo** [comment] 2019-05-07 11:46
Algolia is actually working but the error keeps showing at:

Module 'Magento_Reports':
Module 'Magento_ConfigurableSampleData':
Running data recurring...Required parameter 'theme_dir' was not passed

We have sample data installed. But what is strange that error only shows if Algolia_AlgoliaSearch is enable.

**Comment by webtekindo** [comment] 2019-05-07 11:53
I narrow it down to:

Magento\ConfigurableSampleData\Setup\RecurringData:

`/**
     * Perform full reindex
     */
    public function reindex()
    {
        foreach ($this->indexerCollectionFactory->create()->getItems() as $indexer) {
            $indexer->reindexAll();
        }
    }`


**reindexAll** from that function cause the error _Required parameter 'theme_dir' was not passed_ when Algolia_AlgoliaSearch is enable.

Do you have an idea how to fix it?

**Comment by bsuravech** [comment] 2019-07-14 14:20
Hi @webtekindo! Following up with this issue, were you able to resolve your issue? I'm unfamiliar with this error message myself. Have you tried following the directions in the link you mentioned above to reinstall the theme?

**Comment by bsuravech** [comment] 2019-12-04 15:47
Hi there! I'm closing out this issue as there wasn't a follow up. Please feel free to submit a new issue if this still persisting.

**Closed by bsuravech** 2019-12-04 15:47 UTC
Labels: Investigating

**Comment by abdokouta** [comment] 2020-03-08 15:54
this issue happens to me also after install algolia

**Comment by abdokouta** [comment] 2020-03-09 08:59
I have looked and debugged algolia issue.
Issue is in `Algolia\AlgoliaSearch\Helper\Data::rebuildStoreProductIndexPage()`
