### ISSUE TITLE
Magento Admin panel menu won't work

### ISSUE THREAD

**Issue by Stylish015** [algolia/algoliasearch-magento-2#67] opened 2016-09-07 23:38 UTC
We are using Magento 2.1.0 and have just install:
https://github.com/algolia/algoliasearch-magento-2

After installing this... we can no longer use the Magento Admin menu, no pop out menus will work.

In firefox firebug we get the errors:
![algoliasearch-magento-2](https://cloud.githubusercontent.com/assets/20570886/18332177/a28c1c4e-75b8-11e6-85c5-cfa3ab4b353f.jpg)

Are there any fixes for this?

Thanks.

**Comment by springerin** [comment] 2016-09-08 11:21
disable merge js files. is caused by a missing end of file in the algolia js that goes on top of everythings and so gets merged incorrectly

**Comment by JanPetr** [comment] 2016-09-09 13:44
Fixed in #71, will be part of the next release. Thanks for reporting.

**Closed by JanPetr** 2016-09-09 13:44 UTC
