### ISSUE TITLE
Exception #0 (UnexpectedValueException): Setup version for module 'Algolia_AlgoliaSearch' is not specified

### ISSUE THREAD

**Issue by SerkanYildiz** [algolia/algoliasearch-magento-2#232] opened 2017-05-08 11:25 UTC
Hi,

Today I Installed the plugin via composer in Magento 2.1.6 CE. When I completed the steps in README.md, I got

`Exception #0 (UnexpectedValueException): Setup version for module 'Algolia_AlgoliaSearch' is not specified`.

**Comment by JanPetr** [comment] 2017-05-09 08:27
Hello @SerkanYildiz,

thanks you for your report. You installed the plugin by running `composer require algolia/algoliasearch-magento-2`, right?

When you can see the error message? When you want to load your store in a browser? Thanks for the info.

**Comment by SerkanYildiz** [comment] 2017-05-09 09:32
Hi @JanPetr, Thanks for your reply. 

Right I installed the extension with composer. I got the error message when I tried to visit any of the pages of magento.

**Comment by JanPetr** [comment] 2017-05-09 09:37
Thanks @SerkanYildiz, I will investigate and come back to you.

**Comment by JanPetr** [comment] 2017-05-09 14:25
@SerkanYildiz, could you please check whether the extension was installed from repo.magento.com repository or from packagict.org repository when you ran `composer require algolia/algoliasearch-magento-2` command?

Can you try to run `composer require algolia/algoliasearch-magento-2:1.0.10`?

**Comment by SerkanYildiz** [comment] 2017-05-09 15:01
Hey Jan, I will do it tonight :) Thanks in advance.

**Comment by SerkanYildiz** [comment] 2017-05-09 23:09
Hi @JanPetr I was able to install the extension with `composer require algolia/algoliasearch-magento-2:1.0.10`Thanks!

**Comment by JanPetr** [comment] 2017-05-10 07:08
Hey @SerkanYildiz,

thanks for getting back to me. I know where the problem is - when you install it via composer, but the installation is not done from packagist.org repository, but from repo.magento.com, it ends up with an error, because there is a wrong version on repo.magento.com.
It'll be fixed with the release of version 1.1.0.

Thanks for your help 💯

**Closed by JanPetr** 2017-05-10 07:08 UTC
