### ISSUE TITLE
Incorrect image and thumbnail url for products

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#37] opened 2016-08-11 09:26 UTC
Magento 2.1. Image url doesn`t get url for store(Image is setup as thumbnail, large image) and get broken placeholder url like: /pub/static/adminhtml/_view/en_US/Magento_Catalog/images/product/placeholder/.jpg

**Comment by JanPetr** [comment] 2016-08-11 15:19
Hey @vmalyk,
it seems to be Magento related as we get placeholder URL from Magento directly and bad URL comes from it.
I opened an issue here https://github.com/magento/magento2/issues/6119

**Comment by JanPetr** [comment] 2016-08-15 13:15
@vmalyk, the Magento issue was just labeled as "bug". Let's hope it will be fixed soon.

**Comment by vmalyk** [comment] 2016-08-15 13:34
@JanPetr , Thank you for good news!
But can you look one point - Magento inits thumbnail with another types in imageHelper: [https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/DefaultConfigProvider.php#L389-L392](in model). 
Our test products have set up image, but helper returns placeholder. Can you check that?
And Question: Could indexer be update all data?

**Comment by JanPetr** [comment] 2016-08-15 14:05
Do you mean extension's image helper returns invalid placeholder URL even though your product has image set?

Sorry, I do not undestand your last question. Can you by more specific?

**Comment by vmalyk** [comment] 2016-08-15 14:15
@JanPetr ,  I mean helper return placeholder instead thumbnail url, that set up.
is Product indexer updates all data for all products in Algolia?

**Comment by JanPetr** [comment] 2016-08-16 09:06
Hello @vmalyk, I'm sorry but I'm not sure I follow your issue.

1) Placeholder images - [the extension's ImageHelper](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Image.php) gives you placeholder URL instead of real image URL? Correct?

2) `entity_id` vs. `row_id`, I'm really not sure I got it.
What is the bug in Magento? I checked the code your reference un your links and there is used `entity_id`. Should it be `row_id`? For all version or just for EE?

You are using Magento Enterprise or Community edition?

**Comment by vmalyk** [comment] 2016-08-16 09:34
Hi, @JanPetr 
1. Yes, I got placeholder instead real image. After change 2nd param [here](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/ProductHelper.php#L634) from 'thumbnail' to 'product_thumbnail_image' - it`s fix problem
2. It`s not a bug of Magento. In Enterprise Edition 2.1 Module module-catalog-staging is used and change  tables catalog_category_entity_[type](for ex. table catalog_category_entity_varchar http://prntscr.com/c6c1p8) for support versioning for attributes. Table catalog_category_entity has structure http://prntscr.com/c6c1x6. This should be only for EE 2.1.

I use Magento 2.1 Enterprise Edition.

**Comment by sammarcus** [comment] 2016-10-18 02:52
@JanPetr is this still an ongoing bug in this extension due to there not being a fix for https://github.com/magento/magento2/issues/6119 yet?

I am able to reproduce in 2.0.2, 2.0.8 and 2.1.2 so sadly it does not appear to be limited to >= 2.1.0 as @vmalyk said. I didn't really follow above, is there a functional workaround at the moment so `image_url` accurately reflects the record's path?

**Comment by JanPetr** [comment] 2016-10-18 08:42
Hello @sammarcus,
unfortunately I'm not aware of any workaround. But indexing Base images should work fine:
<img width="937" alt="screenshot 2016-10-18 10 41 36" src="https://cloud.githubusercontent.com/assets/1058144/19470378/95d73476-951f-11e6-930c-d9566497b0ca.png">

**Comment by sammarcus** [comment] 2016-10-18 19:26
Interesting, I have always had that set to Base Image and it still pulls in the faulty placeholder URLs as described above. (FWIW Thumbnail and Small Image also do the same as well)

In the past with M1 I remember I had to go out of my way to mark the image path attributes in `attributesToRetrieve` which I thought was unusual but it did allow the image paths to come in. The same does not seem to be working :/

**Comment by apmson** [comment] 2017-03-07 10:53
`//        $imageHelper = $this->objectManager->create('Algolia\AlgoliaSearch\Helper\Image');
        $imageHelper = $this->objectManager->create('Magento\Catalog\Helper\Image');`

you can use the default magento function replaced it. Algolia\AlgoliaSearch\Helper\Entity\ProductHelper => getObject()

**Comment by Sanfam** [comment] 2017-11-02 21:25
@apmson, I'm troubleshooting the same issue and am having a little trouble understanding what you've described.  From what I gather, you're referring to replacing the stock `$imageHelper` variable and its data source, but you're referring to ProductHelper the next line down while the file that contains this appears to be [CategoryHelper.php Line #183](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/Entity/CategoryHelper.php#L183).  

Would you mind showing a slightly more complete sample of the changes you've implemented to correct this?

**Comment by akashkarev** [comment] 2018-02-08 04:05
Hi Guys,

We had similar problem.
The patch below helped to resolve it.

===================================================================
--- a/etc/view.xml
+++ b/etc/view.xml
@@ -0,0 +1,10 @@
+<?xml version="1.0"?>
+<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/view.xsd">
+    <media>
+        <images module="Magento_Catalog">
+            <image id="image" type="image"/>
+            <image id="small_image" type="image"/>
+            <image id="thumbnail" type="image"/>
+        </images>
+    </media>
+</view>
\ No newline at end of file
===================================================================
--- a/Helper/Data.php
+++ b/Helper/Data.php
@@ -569,7 +569,11 @@

         $this->logger->start('START EMULATION');

-        $this->emulation->startEnvironmentEmulation($storeId);
+        $this->emulation->startEnvironmentEmulation(
+            $storeId,
+            \Magento\Framework\App\Area::AREA_FRONTEND,
+            true
+        );
         $this->emulationRuns = true;

         $this->logger->stop('START EMULATION');

**Comment by JanPetr** [comment] 2018-02-08 10:13
Thanks a bunch for the patch, @akashkarev! 💯 🚀 
I'll give it a try later on and come back to you :)

**Comment by JanPetr** [comment] 2018-02-26 08:19
Thank you so much @akashkarev! Your fix works like a charm! Could you fill [this form](https://docs.google.com/a/algolia.com/forms/d/e/1FAIpQLScFHcqkzw8QoS-XkU1zZ4eOg77K2t88qIXrqOC-828ahyiCnQ/viewform)? I'd like to send you some perks 💯🚀

**Closed** 2018-02-26 10:04 UTC
Labels: Magento
